### ISSUE TITLE
Search for an Expert in Autonomous Drive

### ISSUE THREAD

**Issue by reginaldomoura** [sixauto/sixauto#2]
As a sixauto team member I need to search for an Expert in one of the areas defined by our team in the issue 1#.

- Search for an Expert
- Schedule first 1 hour meeting

**Comment by reginaldomoura** [comment]
We find the OBD Expert - Rui Andrade

**Comment by NunoTMEIA** [comment]
We chose an expert, and we had a first meeting with the expert to understand better the On Board Diagnosis theme. The expert gave us some background on the OBD protocol, but he did not give us what was necessary and indicated another expert who could help us better in the matter.
Now we need to contact that other expert to get more information to start building our knowledge base.
